### ISSUE TITLE
Zipper latency timeout not applied when any inputs are dead

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/trigger#137] opened 2022-06-13 14:23 UTC
In the ongoing VD coldbox triggering tests, an issue was noticed that I think is due to the zipper. No outputs make it through the system until `stop`, when all of the data rushes through the system. A feature of the relevant VD coldbox data taking is that software hit finding is disabled on one of the links (because the machine can't quite keep up with all of the links). So the TPZipper is only getting data from N-1 of its N links.

If I understand the `zipper` code correctly, the items in the `streams` map are only populated when an input is received on the relevant stream (because the input item is needed to calculate the stream ID, the key in the `streams` map). In the `complete()` function, the `streams` object is iterated over, incrementing the `completeness` count and attempting to reach `cardinality`. But if the number of streams seen so far is less than `cardinality`, the condition `completeness >= cardinality` can never be reached, and so everything gets buffered until `TriggerZipper::flush()` is called at "stop" time.

For the short term, we can probably make some workarounds in the configuration, but I think we ought to handle this case. So if I've analyzed things correctly, one possible fix would be to tell `zipper` the stream IDs to expect at configuration time, so it can populate the `streams` member right away. Alternatively, modify the logic in `complete()` somehow to behave differently when the number of streams seen so far is < `cardinality`.

@brettviren , thoughts? If my analysis doesn't sound crazy to you, we can try putting together a test to confirm whether it's correct.

**Comment by brettviren** [comment] 2022-06-13 14:43
Hi @philiprodrigues 

It seems reasonable.  

If a link is a'priori known to be dead, simply omitting it from configuration would avoid the problem (of course).

I think your more general solution to seed the zipper with the set of expected IDs is also reasonable.  It will add some rigidity and complexity to the configuration compared to the current "autodetecting" mode but I think it would not introduce other major issues.

**Comment by philiprodrigues** [comment] 2022-06-13 15:20
Thanks for the quick reply. I'll add this to my to-do list: put together a test and a candidate fix.

**Comment by philiprodrigues** [comment] 2022-07-07 12:51
I've started on trying to implement this. One question is what to set the `last_seen` time in each `Stream` to when we create the streams. The best thing I can think of so far is to set it to the time at run start, but I'm not 100% sure that's right.

**Comment by brettviren** [comment] 2022-07-08 14:19
Hi @philiprodrigues 

I think I agree.  Some more verbose ways to say that:

I see `last_seen` is initialized to `duration_t::min()`.

I think this is reasonable, but it will cause a stream to be considered "tardy" immediately on start when maybe we'd prefer the zipper to be more forgiving.  Once the first message from the stream is received (and likely considered already tardy) then `last_seen` will rectify.  

If we can not deal with loss of this initial message then setting `last_seen` to the run start time would be more perfect.

**Comment by wesketchum** [comment] 2022-10-18 07:04
@CharlieBatchelor I think that you were part of some of the testing of this? Do you know if this has been resolved in recent versions, or is this still something that we need to merge in?

(Maybe @adam-abed-abud knows too...)

**Comment by wesketchum** [comment] 2022-10-18 10:14
OK, will quote a message from @CharlieBatchelor in slack:

> about #137. Phil’s candidate fix did seem to resolve the primary issue of feeding the correct amount of inputs to the zipper if I remember correctly.
> There seems to be an outstanding question of whether we are happy to lose the initial message Brett refers to, or change the `last_seen` to something else (he reasonably suggests run start time!)

**Comment by CharlieBatchelor** [comment] 2022-12-12 09:16
To follow up on this, the ongoing APA tests at EHN1 have shown us that the `cardinality` and `completeness` issue persists. Currently, it seems that `trigger` sets the `cardinality` to the number of links in the hardware map file supplied in the configuration. Unfortunately, there isn't a strict one-to-one mapping between WIB links and active input `TPSet` queues to the `TPZipper`. 

The FW TPG runs currently set up _two input queues only_ for a maximum of 10 physical links. The result is that `completeness` is never achieved since `cardinality` gets set to 10 at config generation, and the maximum number of queues that we actually see `TPSets` on is 2. The current work around is to manually correct the parameter before run time.

Another feature of the FW TPG runs is that occasionally one of the queues can experience "lock-up" at the beginning of the run. As far as I understand, this is a random effect, which cannot be reliably reproduced. This poses another problem for the `TPZipper` in that we cannot confidently set the number of active queues we _will_ see at configuration generation time. 

It has been proposed that we augment the `zipper` logic with a smarter `cardinality`, where the number of active `TPSet` queues is regularly assessed (possibly inside the complete function) and the sending behaviour responds appropriately. This is being investigated in #167 and so we can probably close this issue here.

**Closed as completed by CharlieBatchelor** 2022-12-12 09:16 UTC
